In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../../data/bangladesh food price index.csv")
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,1998-07-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1261.4,27.0182
2,1998-07-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,Wheat,100 KG,actual,Wholesale,BDT,1055.6,22.6101
3,1998-08-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,actual,Wholesale,BDT,1288.75,27.362
4,1998-08-15,Dhaka,Dhaka,Dhaka,23.81,90.41,cereals and tubers,Wheat,100 KG,actual,Wholesale,BDT,1060.0,22.5053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13549,2024-08-15,Sylhet,Maulvibazar,Maulavibazar Sadar,24.491369,91.763765,pulses and nuts,Lentils (masur),KG,aggregate,Retail,BDT,127.5,1.0814
13550,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,cereals and tubers,Rice (coarse),KG,aggregate,Retail,BDT,49.0,0.4156
13551,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,oil and fats,Oil (palm),L,aggregate,Retail,BDT,136.0,1.1535
13552,2024-08-15,Sylhet,Sunamganj,Sunamgonj Sadar,25.072282,91.400318,pulses and nuts,Lentils (masur),KG,aggregate,Retail,BDT,122.5,1.039
13553,2024-08-15,Sylhet,Sylhet,Sylhet Sadar,24.890531,91.871936,cereals and tubers,Wheat flour,KG,aggregate,Retail,BDT,60.0,0.5089

In [4]:
df.drop(columns=['admin1','market', 'category','priceflag', 'pricetype', 'currency','usdprice'],inplace=True)
df = df.drop(0)
df

,date,admin2,latitude,longitude,commodity,unit,price
1,1998-07-15,Dhaka,23.81,90.41,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,1261.4
2,1998-07-15,Dhaka,23.81,90.41,Wheat,100 KG,1055.6
3,1998-08-15,Dhaka,23.81,90.41,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,1288.75
4,1998-08-15,Dhaka,23.81,90.41,Wheat,100 KG,1060.0
5,1998-09-15,Dhaka,23.81,90.41,"Rice (coarse, BR-8/ 11/, Guti Sharna)",100 KG,1415.5
...,...,...,...,...,...,...,...
13549,2024-08-15,Maulvibazar,24.491369,91.763765,Lentils (masur),KG,127.5
13550,2024-08-15,Sunamganj,25.072282,91.400318,Rice (coarse),KG,49.0
13551,2024-08-15,Sunamganj,25.072282,91.400318,Oil (palm),L,136.0
13552,2024-08-15,Sunamganj,25.072282,91.400318,Lentils (masur),KG,122.5
13553,2024-08-15,Sylhet,24.890531,91.871936,Wheat flour,KG,60.0

In [5]:
df['date'] = pd.to_datetime(df['date'])

df = df[df['date'] > "2023-01-01"]
df

,date,admin2,latitude,longitude,commodity,unit,price
4209,2024-09-15,Barguna,22.161255,90.120285,"Potatoes (Holland, white)",KG,52.5
4210,2024-09-15,Barguna,22.161255,90.120285,Wheat flour,KG,51.0
4211,2024-09-15,Barguna,22.161255,90.120285,Eggs (brown),1 piece,13.0
4212,2024-09-15,Barguna,22.161255,90.120285,Sugar,KG,130.0
4213,2024-09-15,Barguna,22.161255,90.120285,Oil (palm),L,142.25
...,...,...,...,...,...,...,...
13549,2024-08-15,Maulvibazar,24.491369,91.763765,Lentils (masur),KG,127.5
13550,2024-08-15,Sunamganj,25.072282,91.400318,Rice (coarse),KG,49.0
13551,2024-08-15,Sunamganj,25.072282,91.400318,Oil (palm),L,136.0
13552,2024-08-15,Sunamganj,25.072282,91.400318,Lentils (masur),KG,122.5
13553,2024-08-15,Sylhet,24.890531,91.871936,Wheat flour,KG,60.0

In [6]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

In [7]:
df['unit'].value_counts()

unit
KG         4359
L          1099
1 piece     307
500 G         8
1 Roll        8
12 KG         5
10 pcs        5
Name: count, dtype: int64

In [8]:
df.loc[df['unit']=='500 G', 'price'] *= 2
df.loc[df['unit']=='12 KG', 'price'] /= 12
df.loc[df['unit']=='10 pcs', 'price'] /= 10

In [9]:
df.drop(columns=['unit'], inplace=True)

In [10]:
df = df.rename(columns={
    "admin2": "place" , 
    "commodity": "product"
})

In [11]:
# Convert date into useful numeric features
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

# Optional: remove original datetime column
df.drop(columns=['date'], inplace=True)

X = df.drop(columns=['price'])
y = df['price']

In [11]:
X

,place,latitude,longitude,product,year,month,day
4209,Barguna,22.161255,90.120285,"Potatoes (Holland, white)",2024,9,15
4210,Barguna,22.161255,90.120285,Wheat flour,2024,9,15
4211,Barguna,22.161255,90.120285,Eggs (brown),2024,9,15
4212,Barguna,22.161255,90.120285,Sugar,2024,9,15
4213,Barguna,22.161255,90.120285,Oil (palm),2024,9,15
...,...,...,...,...,...,...,...
13549,Maulvibazar,24.491369,91.763765,Lentils (masur),2024,8,15
13550,Sunamganj,25.072282,91.400318,Rice (coarse),2024,8,15
13551,Sunamganj,25.072282,91.400318,Oil (palm),2024,8,15
13552,Sunamganj,25.072282,91.400318,Lentils (masur),2024,8,15
13553,Sylhet,24.890531,91.871936,Wheat flour,2024,8,15

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
preprocessor = ColumnTransformer([
    ("ohe", OneHotEncoder(
        drop='first',
        sparse_output=False,
        handle_unknown='ignore'
    ), ['place', 'product']),

    ("std", StandardScaler(),
     ['latitude', 'longitude', 'year', 'month', 'day'])

], remainder='passthrough')

In [13]:
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor

model_pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,      # L1 regularization
        reg_lambda=1.0,     # L2 regularization
        gamma=0,            # min loss reduction
        objective='reg:squarederror',
        random_state=42
    ))
])

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
import numpy as np
from sklearn.metrics import r2_score

def evaluateModelR2Score(model, fit=False):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print("R2 Score", np.round(r2_score(y_test, y_pred), 3))
    return model

In [16]:
model = evaluateModelR2Score(model_pipeline)

R2 Score 0.854

F:\AgenticNutrition\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [18]:
import joblib
joblib.dump(model, "food_price_model.pkl")

['food_price_model.pkl']

In [13]:
df['product'].unique()

<ArrowStringArray>
[            'Potatoes (Holland, white)',
                           'Wheat flour',
                          'Eggs (brown)',
                                 'Sugar',
                            'Oil (palm)',
                         'Chili (green)',
                        'Gourd (bottle)',
                        'Papaya (green)',
                     'Spinach (malabar)',
                'Fish (live, pangasius)',
                       'Lentils (masur)',
              'Garlic (imported, China)',
              'Onions (imported, China)',
                           'Snake gourd',
              'Oil (soybean, fortified)',
                         'Rice (coarse)',
               'Meat (chicken, broiler)',
                        'Bananas (ripe)',
                         'Spinach (red)',
                          'Rice (Kajla)',
                       'Rice (Nurjahan)',
 'Rice (coarse, BR-8/ 11/, Guti Sharna)',
                          'Eggs (white)',
               'Fish (dry, belt 10-12")',
                         'Milk (powder)',
       'Chili (whole, dry, Indian Teja)',
                        'Hyacinth (sim)',
                 'Salt (iodized, Molla)',
                    'Dishwashing liquid',
                     'Laundry detergent',
                          'Toilet paper',
                            'Toothpaste',
                             'Chickpeas',
                       'Bananas (green)',
                               'Carrots',
                             'Eggplants',
                     'Ginger (imported)',
                        'Gourd (bitter)',
                   'Lemon (medium size)',
                       'Oranges (malta)',
                               'Pumpkin',
                        'Tomatoes (red)',
                        'Rice (BRRI-28)',
                        'Rice (BRRI-29)',
                  'Fish (live, tilapia)',
                           'Meat (beef)',
                'Meat (chicken, sonali)',
              'Turmeric (powder, Fresh)',
                          'Bathing soap',
                         'Fuel (diesel)',
                       'Fuel (kerosene)',
                         'Handwash soap',
                         'Oil (mustard)',
                   'Apples (royal gala)',
                               'Cabbage',
               'Cucumber (short, khira)',
              'Onions (imported, India)',
                           'Rice (Gazi)',
                              'Firewood',
                            'Fuel (gas)',
                         'Sanitary pads',
                 'Fish (tilapia, fresh)',
                                  'Milk',
             'Beans (mung, large grain)',
                         'Fuel (petrol)',
                           'Cauliflower',
                        'Ginger (local)']
Length: 67, dtype: str